name: almas_project
description: "A project structure to use for fast flutter project development"
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

scripts:
  build: dart run build_runner build --delete-conflicting-outputs

dependencies:
  cross_file: any
  dio: any
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_secure_storage_x: any
  go_router: any
  hash: ^1.0.4
  hive: any
  hive_flutter: any
  http_parser: any
  json_annotation: any
  package_info_plus: any
  permission_handler: any
  prefman: ^1.2.0
  url_launcher: ^6.3.1
  uuid: any
  copy_with_extension: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  copy_with_extension_gen: ^6.0.0
